import turtle as tr

t = tr.Turtle()

def indexing(index):
    if(index == 0):
        t.penup()
        t.backward(600)
        t.pendown()
def A(index = 1):
    indexing(index)
    t.pensize(10)
    t.left(60)
    t.forward(100)
    t.right(120)
    t.forward(100)
    t.right(180)
    t.penup()
    t.forward(50)
    t.left(60)
    t.pendown()
    t.forward(50)
    t.left(60)
    t.penup()
    t.forward(50)
    t.left(120)
    t.forward(200)
    t.pendown()
# checking drawing letter "A"

def D(index = 1):
    indexing(index)
    t.pensize(10)
    t.forward(25)
    for i in range(18):
        t.left(10)
        t.forward(8)
    t.forward(23)
    t.left(90)
    t.forward(88)
    t.penup()
    t.left(90)
    t.forward(100)
    t.pendown()

def B(index = 1):
    indexing(index)
    t.pensize(10)
    t.forward(25)
    for i in range(18):
        t.left(10)
        t.forward(5)
    t.forward(23)
    t.left(90)
    t.forward(57)
    t.penup()
    t.backward(57)
    t.pendown()
    t.left(90)
    t.forward(25)
    for i in range(18):
        t.left(10)
        t.forward(5)
    t.forward(20)
    t.left(90)
    t.forward(57)
    t.penup()
    t.forward(57)
    t.left(90)
    t.forward(100)
    t.pendown()


def C(index = 1):
    indexing(index)
    t.left(180)
    t.pensize(10)
    t.backward(10)
    t.penup()
    t.forward(10)
    t.pendown()

    for i in range(18):
        t.right(10)
        t.forward(9)
    t.right(90)
    t.penup()
    t.forward(105)
    t.left(90)
    t.forward(90)
    t.pendown()


def E(index = 1):
    indexing(index)
    t.pensize(10)
    t.left(90)
    t.forward(100)
    t.right(90)
    t.forward(50)
    t.right(90)
    t.penup()
    t.forward(50)
    t.right(90)
    t.pendown()
    t.forward(50)
    t.left(90)
    t.penup()
    t.forward(50)
    t.left(90)
    t.pendown()
    t.forward(50)
    t.penup()
    t.forward(90)
    t.pendown()


def F(index = 1):
    indexing(index)
    t.pensize(10)
    t.left(90)
    t.forward(100)
    t.right(90)
    t.forward(50)
    t.right(90)
    t.penup()
    t.forward(50)
    t.right(90)
    t.pendown()
    t.forward(50)
    t.left(90)
    t.penup()
    t.forward(50)
    t.left(90)
    t.forward(100)
    t.pendown()


def G(index = 1):
    indexing(index)
    t.left(90)
    t.pensize(10)
    t.penup()
    t.forward(30)
    t.pendown()
    t.forward(30)
    t.left(90)
    t.forward(30)
    t.right(180)
    t.penup()
    t.forward(30)
    t.right(90)
    t.forward(30)
    t.pendown()
    for i in range(10):
        t.right(30)
        t.forward(30)
    t.penup()
    t.backward(30)
    t.left(30)
    t.forward(100)
    t.right(90)
    t.forward(110)
    t.left(90)
    t.pendown()
        


def H(index = 1):
    indexing(index)
    t.pensize(10)
    t.left(90)
    t.forward(100)
    t.penup()
    t.right(180)
    t.forward(50)
    t.left(90)
    t.pendown()
    t.forward(50)
    t.left(90)
    t.forward(50)
    t.penup()
    t.right(180)
    t.forward(50)
    t.pendown()
    t.forward(50)
    t.left(90)
    t.penup()
    t.forward(60)
    t.pendown()

def I(index = 1):
    indexing(index)
    t.pensize(10)
    t.forward(50)
    t.left(180)
    t.penup()
    t.forward(25)
    t.right(90)
    t.pendown()
    t.forward(100)
    t.right(90)
    t.forward(25)
    t.left(180)
    t.penup()
    t.forward(25)
    t.pendown()
    t.forward(25)
    t.penup()
    t.backward(150)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.pendown()
    

def J(index = 1):
    indexing(index)
    t.pensize(10)
    t.right(90)
    for i in range(12):
        t.left(15)
        t.forward(9)
    t.forward(91)
    t.left(90)
    t.forward(50)
    t.penup()
    t.backward(150)
    t.left(90)
    t.forward(120)
    t.left(90)
    t.pendown()


def K(index = 1):
    indexing(index)
    t.pensize(10)
    t.left(90)
    t.forward(120)
    t.right(180)
    t.penup()
    t.forward(60)
    t.left(140)
    t.pendown()
    t.forward(75)
    t.right(180)
    t.penup()
    t.forward(75)
    t.right(280)
    t.pendown()
    t.forward(75)
    t.right(180)
    t.forward(75)
    t.right(220)
    t.forward(60)
    t.left(90)
    t.penup()
    t.forward(120)
    t.pendown()


def L(index = 1):
    indexing(index)
    t.pensize(10)
    t.left(90)
    t.forward(100)
    t.penup()
    t.backward(100)
    t.right(90)
    t.pendown()
    t.forward(75)
    t.penup()
    t.forward(80)
    t.pendown()


def M(index = 1):
    indexing(index)
    t.pensize(10)
    t.left(90)
    t.forward(100)
    t.right(120)
    t.forward(50)
    t.left(60)
    t.forward(50)
    t.right(120)
    t.forward(100)
    t.left(90)
    t.penup()
    t.forward(80)
    t.pendown()


def N(index = 1):
    indexing(index)
    t.pensize(10)
    t.left(90)
    t.forward(100)
    t.right(150)
    t.forward(117)
    t.right(210)
    t.forward(100)
    t.penup()
    t.backward(100)
    t.right(90)
    t.forward(150)
    t.pendown()


def O(index = 1):
    indexing(index)
    t.pensize(10)
    t.left(90)
    t.penup()
    t.forward(10)
    t.right(90)
    t.forward(20)
    t.pendown()
    for i in range(180):
        t.forward(2)
        t.left(2)
    t.penup()
    t.forward(120)
    t.pendown()

def P(index = 1):
    indexing(index)
    t.pensize(10)
    t.left(90)
    t.forward(120)
    for i in range(18):
        t.right(20)
        t.forward(20)
    t.penup()
    t.backward(120)
    t.right(90)
    t.forward(200)
    t.pendown()


def Q(index = 1):
    indexing(index)
    t.pensize(10)
    for i in range(180):
        t.forward(2)
        t.left(2)
    for i in range(10):
        t.forward(2)
        t.left(2)
    t.left(90)
    t.forward(20)
    t.backward(60)
    t.penup()
    t.forward(40)
    t.right(108)
    t.forward(100)

      
def R(index = 1):
    indexing(index)
    t.pensize(10)
    t.left(90)
    t.forward(100)
    t.right(90)
    for i in range(20):
        t.right(8)
        t.forward(5)
    t.left(180)
    t.right(60)
    t.forward(50)
    t.left(40)
    t.penup()
    t.forward(80)
    t.pendown()    


def S(index = 1):
    indexing(10)
    t.pensize(10)
    t.forward(10)
    for i in range(20):
        t.left(8)
        t.forward(5)
    t.forward(10)
    for i in range(20):
        t.right(8)
        t.forward(5)
    t.forward(10)    
    t.right(90)
    t.penup()    
    t.forward(150)
    t.left(90)
    t.forward(100)
    t.pendown()


def T(index = 1):
    indexing(index)
    t.pensize(10)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(50)
    t.penup()
    t.backward(50)
    t.pendown()
    t.backward(50)
    t.penup()
    t.forward(50)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.pendown()


def U(index = 1):
    indexing(index)
    t.pensize(10)
    t.left(90)
    t.forward(100)
    t.penup()
    t.backward(100)
    t.right(180)
    t.pendown()
    for i in range(12):
        t.right(15)
        t.forward(9)
    t.forward(90)   
    t.penup()
    t.backward(100)
    t.right(90)
    t.forward(120)
    t.pendown()     


def V(index = 1):
    indexing(index)
    t.pensize(10)
    t.left(120)
    t.forward(100)
    t.penup()
    t.backward(100)
    t.pendown()
    t.right(60)
    t.forward(100)
    t.penup()
    t.backward(100)
    t.right(60)
    t.forward(100)
    t.pendown()


def W(index = 1):
    indexing(index)
    t.pensize(10)
    t.left(90)
    t.forward(100)
    t.penup()
    t.backward(100)
    t.pendown()
    t.right(30)
    t.forward(50)
    t.right(120)
    t.forward(50)
    t.left(150)
    t.forward(100)
    t.penup()
    t.backward(100)
    t.right(90)
    t.forward(90)
    t.pendown()


def X(index = 1):
    indexing(index)
    t.pensize(10)
    t.left(120)
    t.forward(100)
    t.right(120)
    t.penup()
    t.forward(50)
    t.right(120)
    t.pendown()
    t.forward(100)
    t.left(120)
    t.penup()
    t.forward(110)
    t.pendown()


def Y(index = 1):
    indexing(index)
    t.pensize(10)
    t.left(90)
    t.forward(70)
    t.left(30)
    t.forward(80)
    t.penup()
    t.backward(80)
    t.pendown()
    t.right(60)
    t.forward(80)
    t.penup()
    t.backward(80)
    t.left(30)
    t.backward(70)
    t.right(90)
    t.forward(110)
    t.pendown()

def Z(index = 1):
    indexing(index)
    t.pensize(10)
    t.right(180)
    t.forward(80)
    t.right(120)
    t.forward(150)
    t.left(120)
    t.forward(80)
    t.left(90)
    t.penup()
    t.forward(127)
    t.left(90)
    t.penup()
    t.forward(180)
    t.pendown()

    
